using System;
using System.Collections;
using System.Text;
using Firebase;
using Firebase.Auth;
using TMPro;
using UnityEngine;
using UnityEngine.Networking;
using UnityEngine.UI;

/// <summary>
/// One-time device-connect code gate shown before <see cref="WelcomeScreenController"/>.
/// The child enters the 6-digit code shown on the parent's dashboard (parent dashboard
/// itself is a separate, not-yet-built client; for now the code is generated by calling
/// backend-heal's POST /auth/otp/generate directly). On success the code is verified via
/// POST /auth/otp/verify, exchanged for a Firebase custom token, and the device signs in.
///
/// Firebase Auth persists the session on-device, so if <see cref="FirebaseAuth.CurrentUser"/>
/// is already set on launch, this screen is skipped entirely -- no manual "remember me"
/// storage needed.
/// </summary>
public class LoginScreenController : MonoBehaviour
{
    [Header("Screens")]
    public GameObject loginScreen;
    public CanvasGroup loginGroup;

    [Tooltip("What Login opens on success (Welcome).")]
    public GameObject nextScreen;
    public CanvasGroup nextGroup;
    public float crossFadeDuration = 0.8f;

    [Header("Code Entry")]
    [Tooltip("Exactly 6 single-character TMP_InputField boxes, left to right.")]
    public TMP_InputField[] digitFields = new TMP_InputField[6];
    public Button submitButton;
    public TMP_Text errorText;

    [Header("Backend")]
    public string baseUrl = "http://localhost:3003";

    private FirebaseAuth auth;
    private bool submitting;
    private bool transitioning;
#if UNITY_EDITOR
    // The Firebase Unity SDK's macOS Editor support is missing the native
    // FirebaseCppApp library (only Windows/Linux binaries ship in the SDK),
    // so CheckAndFixDependenciesAsync throws DllNotFoundException here.
    // This bypass lets the login UI/flow be iterated on in-Editor; it never
    // compiles into a real device build.
    private const string MockSignedInKey = "EditorMockSignedIn";
    private bool mockAuthMode;
#endif

    void Start()
    {
        if (loginScreen != null) loginScreen.SetActive(true);
        if (nextScreen != null) nextScreen.SetActive(false);
        HideError();

        for (int i = 0; i < digitFields.Length; i++)
        {
            int index = i;
            if (digitFields[i] != null)
                digitFields[i].onValueChanged.AddListener(value => OnDigitChanged(index, value));
        }

        if (submitButton != null) submitButton.onClick.AddListener(Submit);

        StartCoroutine(InitializeFirebaseAndCheckSession());
    }

    private IEnumerator InitializeFirebaseAndCheckSession()
    {
        System.Threading.Tasks.Task<DependencyStatus> dependencyTask = null;
        bool threw = false;
        try
        {
            dependencyTask = FirebaseApp.CheckAndFixDependenciesAsync();
        }
        catch (Exception e)
        {
            Debug.LogWarning($"[Login] FirebaseApp.CheckAndFixDependenciesAsync threw synchronously ({e.GetType().Name}): {e.Message}");
            threw = true;
        }

#if UNITY_EDITOR
        if (threw || dependencyTask == null)
        {
            EnterMockAuthMode();
            yield break;
        }

        // On some platforms (this macOS Editor included, whose Firebase Unity SDK
        // import lacks the native FirebaseCppApp binary) the dependency check task
        // never completes instead of faulting synchronously. Give it a few seconds,
        // then fall back to the Editor mock rather than hang the login screen forever.
        float timeout = 5f;
        float elapsed = 0f;
        while (!dependencyTask.IsCompleted && elapsed < timeout)
        {
            elapsed += Time.deltaTime;
            yield return null;
        }

        if (!dependencyTask.IsCompleted)
        {
            Debug.LogWarning("[Login] Firebase dependency check did not complete within timeout in this Editor -> using Editor mock auth for iteration. This bypass never compiles into a real build.");
            EnterMockAuthMode();
            yield break;
        }
#else
        yield return new WaitUntil(() => dependencyTask.IsCompleted);
#endif

        if (dependencyTask.IsFaulted || dependencyTask.Result != DependencyStatus.Available)
        {
            Debug.LogError($"[Login] Firebase dependencies unavailable: {(dependencyTask.IsFaulted ? dependencyTask.Exception.ToString() : dependencyTask.Result.ToString())}");
            yield break;
        }

        auth = FirebaseAuth.DefaultInstance;

        if (auth.CurrentUser != null)
        {
            Debug.Log("[Login] Existing Firebase session found -> skipping login");
            EnterNextScreenImmediately();
        }
    }

#if UNITY_EDITOR
    private void EnterMockAuthMode()
    {
        mockAuthMode = true;
        if (PlayerPrefs.GetInt(MockSignedInKey, 0) == 1)
        {
            Debug.Log("[Login] Mock session found -> skipping login");
            EnterNextScreenImmediately();
        }
    }
#endif

    private void EnterNextScreenImmediately()
    {
        if (loginScreen != null) loginScreen.SetActive(false);
        if (nextScreen != null) nextScreen.SetActive(true);
        if (nextGroup != null) nextGroup.alpha = 1f;
    }

    private void OnDigitChanged(int index, string value)
    {
        if (string.IsNullOrEmpty(value))
        {
            if (index > 0)
            {
                digitFields[index - 1].Select();
                digitFields[index - 1].ActivateInputField();
            }
            return;
        }

        char c = value[value.Length - 1];
        if (!char.IsDigit(c))
        {
            digitFields[index].SetTextWithoutNotify("");
            return;
        }

        if (digitFields[index].text != c.ToString())
            digitFields[index].SetTextWithoutNotify(c.ToString());

        if (index < digitFields.Length - 1)
        {
            digitFields[index + 1].Select();
            digitFields[index + 1].ActivateInputField();
        }
        else
        {
            digitFields[index].DeactivateInputField();
        }

        if (AllDigitsFilled())
            Submit();
    }

    private bool AllDigitsFilled()
    {
        foreach (var field in digitFields)
        {
            if (field == null || field.text.Length != 1) return false;
        }
        return true;
    }

    /// <summary>Wired to the Submit button's OnClick; also auto-called once the 6th digit is entered.</summary>
    public void Submit()
    {
        if (submitting || transitioning) return;
#if UNITY_EDITOR
        if (auth == null && !mockAuthMode) return;
#else
        if (auth == null) return;
#endif
        if (!AllDigitsFilled()) return;

        var code = new StringBuilder(digitFields.Length);
        foreach (var field in digitFields) code.Append(field.text);

#if UNITY_EDITOR
        if (mockAuthMode)
        {
            Debug.Log("[Login] Editor mock auth -> any 6-digit code is accepted, skipping backend verify call");
            StartCoroutine(SignIn("mock-token"));
            return;
        }
#endif
        StartCoroutine(VerifyCode(code.ToString()));
    }

    private IEnumerator VerifyCode(string code)
    {
        submitting = true;
        SetInteractable(false);
        HideError();

        string json = "{\"code\":\"" + code + "\"}";
        byte[] bodyRaw = Encoding.UTF8.GetBytes(json);

        using (var request = new UnityWebRequest($"{baseUrl}/auth/otp/verify", "POST"))
        {
            request.uploadHandler = new UploadHandlerRaw(bodyRaw);
            request.downloadHandler = new DownloadHandlerBuffer();
            request.SetRequestHeader("Content-Type", "application/json");

            yield return request.SendWebRequest();

            if (request.result != UnityWebRequest.Result.Success)
            {
                Debug.LogWarning($"[Login] Verify failed: {request.error} / {request.downloadHandler.text}");
                FailAndReset("Wrong code, try again");
                yield break;
            }

            VerifyResponse response = null;
            try
            {
                response = JsonUtility.FromJson<VerifyResponse>(request.downloadHandler.text);
            }
            catch (Exception e)
            {
                Debug.LogError($"[Login] Failed to parse verify response: {e.Message}");
            }

            if (response == null || string.IsNullOrEmpty(response.token))
            {
                FailAndReset("Something went wrong, try again");
                yield break;
            }

            yield return SignIn(response.token);
        }
    }

    private IEnumerator SignIn(string token)
    {
#if UNITY_EDITOR
        if (mockAuthMode)
        {
            Debug.Log("[Login] Mock sign-in (Editor bypass) -> cross-fading to next screen");
            PlayerPrefs.SetInt(MockSignedInKey, 1);
            PlayerPrefs.Save();
            transitioning = true;
            yield return CrossFade();
            yield break;
        }
#endif
        var signInTask = auth.SignInWithCustomTokenAsync(token);
        yield return new WaitUntil(() => signInTask.IsCompleted);

        if (signInTask.IsFaulted || signInTask.IsCanceled)
        {
            Debug.LogError($"[Login] Firebase sign-in failed: {signInTask.Exception}");
            FailAndReset("Something went wrong, try again");
            yield break;
        }

        Debug.Log("[Login] Signed in -> cross-fading to next screen");
        transitioning = true;
        yield return CrossFade();
    }

    private IEnumerator CrossFade()
    {
        if (nextScreen != null) nextScreen.SetActive(true);
        if (nextGroup != null) nextGroup.alpha = 0f;

        float startLogin = loginGroup != null ? loginGroup.alpha : 1f;
        float t = 0f;
        while (t < 1f)
        {
            t += Time.deltaTime / Mathf.Max(0.01f, crossFadeDuration);
            float eased = Mathf.SmoothStep(0f, 1f, Mathf.Clamp01(t));
            if (loginGroup != null) loginGroup.alpha = Mathf.Lerp(startLogin, 0f, eased);
            if (nextGroup != null) nextGroup.alpha = eased;
            yield return null;
        }

        if (nextGroup != null) nextGroup.alpha = 1f;
        if (loginScreen != null) loginScreen.SetActive(false);
        Debug.Log("[Login] Cross-fade complete -> login hidden, next screen active");
    }

    private void FailAndReset(string message)
    {
        ShowError(message);
        ClearDigits();
        submitting = false;
        SetInteractable(true);
    }

    private void SetInteractable(bool interactable)
    {
        foreach (var field in digitFields)
        {
            if (field != null) field.interactable = interactable;
        }
        if (submitButton != null) submitButton.interactable = interactable;
    }

    private void ClearDigits()
    {
        foreach (var field in digitFields)
        {
            if (field != null) field.SetTextWithoutNotify("");
        }
        if (digitFields.Length > 0 && digitFields[0] != null)
        {
            digitFields[0].Select();
            digitFields[0].ActivateInputField();
        }
    }

    private void ShowError(string message)
    {
        if (errorText == null) return;
        errorText.text = message;
        errorText.gameObject.SetActive(true);
    }

    private void HideError()
    {
        if (errorText != null) errorText.gameObject.SetActive(false);
    }

    [Serializable]
    private class VerifyResponse
    {
        public string token;
        public string role;
    }

#if UNITY_EDITOR
    [UnityEditor.MenuItem("Tri-Heal/Login/Clear Editor Mock Session")]
    private static void ClearMockSession()
    {
        PlayerPrefs.DeleteKey(MockSignedInKey);
        PlayerPrefs.Save();
        Debug.Log("[Login] Cleared Editor mock session -> next Play will show Login again");
    }
#endif
}
